### ISSUE TITLE
Add CI via travis or azure or something

### ISSUE THREAD

**Issue by snakescott** [snakescott/awesome-dumpsterfire#2]
start with just enforcing precommit

**Comment by snakescott** [comment]
@asottile any suggestions on what the best CI to integrate with is?

**Comment by asottile** [comment]
I can take this one :D

**Comment by snakescott** [comment]
sweet thx!

**Comment by asottile** [comment]
Can you give me more rights? I don't have enough to add webhooks to set up CI with :D

**Comment by snakescott** [comment]
ugh, I don't think this is possible on a personal repo.

Is it better for me to just hand-jam the webhook config settings you give me, or should I move this project to like a `dumpsterfire` organization lol.

**Comment by snakescott** [comment]
you github way better than I do so just LMK :-D

**Comment by asottile** [comment]
hmm yeah shoot you're right personal repos only have "can commit" access and can't add more permissions 🤔 

I was going to set up azure pipelines but it might be easier for you to flick the switch on travis-ci and then I can just set that up instead

that way we don't have to do any org juggling 😆

**Comment by snakescott** [comment]
kk, how do I "flip the switch"? Follow https://docs.travis-ci.com/user/tutorial/, or something else?

**Comment by asottile** [comment]
I'm still not quite sure how to do it on travis-ci.com

On travis-ci.org it's through the settings menu in the top right, there should be a list of repositories and you change the little switch from off to on

**Comment by snakescott** [comment]
Done:

https://travis-ci.org/snakescott/awesome-dumpsterfire
